repos:
  - repo: local
    hooks:
      - id: gofumpt
        name: gofumpt (strict gofmt)
        entry: gofumpt -w
        language: system
        files: \.go$
      - id: golines
        name: golines (wrap long lines)
        entry: golines -w
        language: system
        files: \.go$

