services:
  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_USER: gosanta
      POSTGRES_PASSWORD: gosanta
      POSTGRES_DB: gosanta
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

